name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            preset-configure: linux-gcc-debug      
            preset-build: build-linux-release
            artifact-path: ./out/build/linux-gcc-debug/CppProgrammingLab2
            test-path: ./out/build/linux-gcc-debug/ip_tests   
          - os: windows-latest
            preset-configure: windows-mingw-release
            preset-build: build-windows-release
            artifact-path: ./out/build/windows-mingw-release/CppProgrammingLab2.exe
            test-path: ./out/build/windows-mingw-release/ip_tests.exe 

    runs-on: ${{ matrix.os }}
    permissions: write-all
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools & GTest (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gcc g++ libgtest-dev  # ОБЯЗАТЕЛЬНО ставим libgtest-dev
      
      - name: CMake Configure
        run: cmake --preset ${{ matrix.preset-configure }}

      - name: CMake Build
        run: cmake --build --preset ${{ matrix.preset-build }}

        scrimmage-name: Run Unit Tests
        run: |
          echo "Running Google Tests..."
          ${{ matrix.test-path }}

      - name: Run Program to Test Sanitizers (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Run programm with input data"
          # Чтобы программа не зависла на чтении cin, передаем ей пустой поток или тестовый файл
          ${{ matrix.artifact-path }} < ./data/ip_filter.tsv

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.${{ github.run_number }}
          name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: ${{ matrix.artifact-path }}
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
